### ISSUE TITLE
using with k8s nginx-ingress-controller 

### ISSUE THREAD

**Issue by yawboateng** [infiniroot/nginx-mitigate-log4shell#6]
i tried adding this to the `server-snippet` block on the nginx ingress controller configmap but doesnt seem to work, headers with `jndi` are allowed through. any idea how to go about it?

**Comment by karteek** [comment]
Restarting of pods seem to do the trick.

**Comment by ZabbensX** [comment]
@yawboateng server-snippet is not enough at all.
You need to build a plugin. We did this within a configmap
Mount the cm and load it via nginx-cm
Reboot ingress-nginx

We also enhanced the script to parse body and arguments too (needed?).
To parse the body you need a server-snippet.

I attached our work so far - maybe someone want's to merge it to this repo.
And clean the code, it is very ugly at this point but working. Also htmldecode is implemented.

[lua-cm.yaml.txt](https://github.com/infiniroot/nginx-mitigate-log4shell/files/7710321/lua-cm.yaml.txt)
[ingress-cm.yaml.txt](https://github.com/infiniroot/nginx-mitigate-log4shell/files/7710339/ingress-cm.yaml.txt)
[ingress.yaml.txt](https://github.com/infiniroot/nginx-mitigate-log4shell/files/7710350/ingress.yaml.txt)

**Comment by Napsty** [comment]
@ZabbensX wow. great work!

**Comment by yawboateng** [comment]
@ZabbensX great work! thanks for sharing!!

**Comment by Napsty** [comment]
@ZabbensX if you don't mind, I would like to add this into the repo, in a sub directory, e.g. "ingress" or "kubernetes-ingress". We can adjust the current txt files with the updated lua script.

**Comment by ZabbensX** [comment]
@Napsty yes please i am too busy to make a merge request.
